<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SeeSight.Identity.Application\SeeSight.Identity.Application.csproj" />
    <ProjectReference Include="..\SeeSight.Identity.Domain\SeeSight.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\SeeSight.SharedKernel\SeeSight.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\Shared\SeeSight.Shared.Common\SeeSight.Shared.Common.csproj" />
  </ItemGroup>

</Project>
