<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Services\Identity\SeeSight.Identity.Domain\SeeSight.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Identity\SeeSight.Identity.Application\SeeSight.Identity.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Identity\SeeSight.Identity.Infrastructure\SeeSight.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Identity\SeeSight.Identity.Api\SeeSight.Identity.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
